### ISSUE TITLE
manually create docker for local testnet as WSL environment not supported?

### ISSUE THREAD

**Issue by eino-makitalo** [Kava-Labs/kvtool#174]
In WSL when giving command 

 kvtool testnet bootstrap
 
 it fails 
 `[+] Running 0/0
 ⠋ kavanode Pulling                                                                                                0.0s
error getting credentials - err: fork/exec /usr/bin/docker-credential-desktop.exe: exec format error, out: ``
exit status 1
[+] Running 0/0
 ⠋ kavanode Pulling                                                                                                0.0s
error getting credentials - err: fork/exec /usr/bin/docker-credential-desktop.exe: exec format error, out: ``
exit status 1`

Probably this docker for local testnet could be build also manually?

**Comment by pirtleshell** [comment]
hi @eino-makitalo,

apologies we don't monitor these issues 😅 

there is a `gen-config` command that will just generate the docker-compose setup:
```
kvtool testnet gen-config kava --generated-dir path/to/output/dir
```
note that when building kvtool, the generated-dir will default to `<repo-location>/full_configs/generated`

you should be able to `docker compose up` from there to get the chain running locally.
